### PR TITLE
Fix reloading the integration from hanging

### PR DESCRIPTION
**Pull request by knightzac19**
When doing reload on the integration, it would always hang and all entities would become unavailable. This would require homeassistant to completely reboot before the integration would work again. Changing it to use the built in platforms unload function has fixed this behavior.

### CODE REVIEW

**Comment by knightzac19** [comment]
@dotvezz fixed my branch from the main merge, should pass workflows now.

**Comment by Anto79-ops** [comment]
thanks for this PR. Sometimes my machine would go offline (wifi connection issue), and I would try to reload it, and that issue happens. Now, if I reload it, will it attemp to connecto the machine?

**Comment by knightzac19** [comment]
Yea, if the entity isn't showing "unavailable"(it should still work if it is, just didn't test that scenario as much), reload should work now. I tested my 475 by kicking it off wifi and then reloading, it correctly reconnected and started working again.

**Comment by Anto79-ops** [comment]
thanks!

**Pull request merged**
